# Generated by Django 4.1.3 on 2023-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_orderplaced_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('A', 'Atta'), ('C', 'Chhola'), ('CO', 'Cooking Oil'), ('K', 'Kitchen'), ('R', 'Rice'), ('DP', 'Dal/Pulses')], max_length=2),
        ),
    ]
