# Generated by Django 4.1.6 on 2023-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderplaced_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_signature',
        ),
        migrations.AddField(
            model_name='cart',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='razorpay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
