# Generated by Django 4.1.6 on 2023-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_orderplaced_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
