# Generated by Django 4.1.6 on 2023-03-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
